#!/usr/bin/env bash
# Record the third-party skills installed on this machine:
#
#   1. copies ~/.agents/.skill-lock.json into the repo
#   2. regenerates the skill table in README.md from it
#
# Run it after installing, updating, or removing a skill, then commit the diff.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIVE="$HOME/.agents/.skill-lock.json"
LOCK_FILE="$REPO_DIR/reference-skill-lock.json"
README="$REPO_DIR/README.md"
INSTALLED_DIR="$HOME/.agents/skills"

START_MARKER="<!-- skills:start -->"
END_MARKER="<!-- skills:end -->"

# shellcheck source=lockfile.sh
source "$REPO_DIR/lockfile.sh"

if [[ ! -f "$LIVE" ]]; then
  echo "error: no lock file at $LIVE. Nothing to sync." >&2
  exit 1
fi

if ! grep -qF "$START_MARKER" "$README" || ! grep -qF "$END_MARKER" "$README"; then
  echo "error: $README is missing the $START_MARKER / $END_MARKER pair." >&2
  exit 1
fi

cp "$LIVE" "$LOCK_FILE"
echo "copied $LIVE -> $LOCK_FILE"

# first_sentence <skill-name> prints the opening sentence of that skill's
# description, read from the copy installed on this machine.
first_sentence() {
  local name="$1" file="$INSTALLED_DIR/$1/SKILL.md" desc

  [[ -f "$file" ]] || return 0

  desc="$(awk '/^description:/ { sub(/^description:[[:space:]]*/, ""); print; exit }' "$file")"
  desc="${desc%\"}"
  desc="${desc#\"}"
  desc="${desc%\'}"
  desc="${desc#\'}"

  # Cut at the first sentence break, then put the period back.
  desc="${desc%%. *}"
  [[ "$desc" == *. ]] || desc="$desc."

  # A bare pipe would end the table cell early.
  echo "${desc//|/\\|}"
}

TABLE="$(mktemp)"
trap 'rm -f "$TABLE"' EXIT

{
  echo "$START_MARKER"
  echo
  echo "Generated by \`sync.sh\`, do not edit by hand. Install any single row with"
  echo "\`npx skills add <from>@<skill> -g -y\`, or all of them with \`./bootstrap.sh\`."
  echo
  echo "| Skill | What it does | From |"
  echo "| --- | --- | --- |"

  while IFS=$'\t' read -r name source source_type source_url; do
    [[ -z "$name" ]] && continue
    repo_url="${source_url%.git}"
    if [[ -n "$repo_url" ]]; then
      from="[$source]($repo_url)"
    else
      from="$source"
    fi
    echo "| \`$name\` | $(first_sentence "$name") | $from |"
  done < <(lock_rows "$LOCK_FILE")

  echo
  echo "$END_MARKER"
} > "$TABLE"

awk -v start="$START_MARKER" -v end="$END_MARKER" -v table="$TABLE" '
  $0 == start { while ((getline line < table) > 0) print line; skipping = 1; next }
  $0 == end   { skipping = 0; next }
  !skipping   { print }
' "$README" > "$README.tmp"
mv "$README.tmp" "$README"

echo "wrote  the skill table in $README"
git -C "$REPO_DIR" --no-pager diff --stat -- "$LOCK_FILE" "$README"
