#!/usr/bin/env bash
# Record every skill this machine has, mine and other people's:
#
#   1. copies ~/.agents/.skill-lock.json into the repo
#   2. regenerates the third-party tables in README.md from it, one per source
#   3. regenerates the table of my own skills from skills/*/SKILL.md
#
# Run it after installing, updating, or removing a skill, or after editing one
# of my descriptions, then commit the diff.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIVE="$HOME/.agents/.skill-lock.json"
LOCK_FILE="$REPO_DIR/reference-skill-lock.json"
README="$REPO_DIR/README.md"
INSTALLED_DIR="$HOME/.agents/skills"
MINE_DIR="$REPO_DIR/skills"

START_MARKER="<!-- skills:start -->"
END_MARKER="<!-- skills:end -->"
MINE_START_MARKER="<!-- mine:start -->"
MINE_END_MARKER="<!-- mine:end -->"

# shellcheck source=lockfile.sh
source "$REPO_DIR/lockfile.sh"

if [[ ! -f "$LIVE" ]]; then
  echo "error: no lock file at $LIVE. Nothing to sync." >&2
  exit 1
fi

require_markers() {
  local start="$1" end="$2"

  if ! grep -qF "$start" "$README" || ! grep -qF "$end" "$README"; then
    echo "error: $README is missing the $start / $end pair." >&2
    exit 1
  fi
}

require_markers "$START_MARKER" "$END_MARKER"
require_markers "$MINE_START_MARKER" "$MINE_END_MARKER"

cp "$LIVE" "$LOCK_FILE"
echo "copied $LIVE -> $LOCK_FILE"

# first_sentence <skill-md-path> prints the opening sentence of that skill's
# description, read from its front matter.
first_sentence() {
  local file="$1" desc

  [[ -f "$file" ]] || return 0

  desc="$(awk '/^description:/ { sub(/^description:[[:space:]]*/, ""); print; exit }' "$file")"
  desc="${desc%\"}"
  desc="${desc#\"}"
  desc="${desc%\'}"
  desc="${desc#\'}"

  # Cut at the first sentence break, then put the period back.
  desc="${desc%%. *}"
  [[ "$desc" == *. ]] || desc="$desc."

  # A bare pipe would end the table cell early.
  echo "${desc//|/\\|}"
}

# splice <start-marker> <end-marker> <file> replaces everything between the two
# markers in README.md with the contents of <file>, markers included.
splice() {
  local start="$1" end="$2" block="$3"

  awk -v start="$start" -v end="$end" -v block="$block" '
    $0 == start { while ((getline line < block) > 0) print line; skipping = 1; next }
    $0 == end   { skipping = 0; next }
    !skipping   { print }
  ' "$README" > "$README.tmp"
  mv "$README.tmp" "$README"
}

BLOCK="$(mktemp)"
ROWS="$(mktemp)"
trap 'rm -f "$BLOCK" "$ROWS"' EXIT

# My own skills, one row each, in the order they sit on disk.
{
  echo "$MINE_START_MARKER"
  echo
  echo "Generated by \`sync.sh\` from \`skills/*/SKILL.md\`, do not edit by hand."
  echo
  echo "| Skill | What it does |"
  echo "| --- | --- |"

  for dir in "$MINE_DIR"/*/; do
    name="$(basename "$dir")"
    [[ -f "$dir/SKILL.md" ]] || continue
    echo "| \`$name\` | $(first_sentence "$dir/SKILL.md") |"
  done

  echo
  echo "$MINE_END_MARKER"
} > "$BLOCK"

splice "$MINE_START_MARKER" "$MINE_END_MARKER" "$BLOCK"

lock_rows "$LOCK_FILE" > "$ROWS"

# Everyone else's skills, grouped into one table per source.
{
  echo "$START_MARKER"
  echo
  echo "Generated by \`sync.sh\`, do not edit by hand. One table per source, biggest"
  echo "first. Install any single row with \`npx skills add <from>@<skill> -g -y\`, or"
  echo "all of them with \`./bootstrap.sh\`."

  # Sources, most skills first, ties broken by name. Bash 3.2 on macOS has no
  # associative arrays, so grouping is one pass over $ROWS per source.
  while read -r count source; do
    [[ -z "$source" ]] && continue

    source_url="$(awk -F'\t' -v s="$source" '$2 == s { print $4; exit }' "$ROWS")"
    repo_url="${source_url%.git}"
    if [[ -n "$repo_url" ]]; then
      heading="[$source]($repo_url)"
    else
      heading="$source"
    fi

    echo
    if [[ "$count" -eq 1 ]]; then
      echo "### $heading, 1 skill"
    else
      echo "### $heading, $count skills"
    fi
    echo
    echo "| Skill | What it does |"
    echo "| --- | --- |"

    while IFS=$'\t' read -r name row_source _ _; do
      [[ "$row_source" == "$source" ]] || continue
      echo "| \`$name\` | $(first_sentence "$INSTALLED_DIR/$name/SKILL.md") |"
    done < "$ROWS"
  done < <(cut -f2 "$ROWS" | sort | uniq -c | sort -k1,1nr -k2,2 | sed 's/^ *//')

  echo
  echo "$END_MARKER"
} > "$BLOCK"

splice "$START_MARKER" "$END_MARKER" "$BLOCK"

echo "wrote  both skill tables in $README"
git -C "$REPO_DIR" --no-pager diff --stat -- "$LOCK_FILE" "$README"
